version: '3.9'
services:
  db:
    container_name: db
    image: postgres:16.3
    restart: always
    env_file:
      - .env
    environment:
      - POSTGRES_DB=${PG_DB}
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_PASSWORD=${PG_PASS}
    ports:
      - ${PG_PORT}:${PG_PORT}
    volumes:
      - db-data:/var/lib/postgres/data

volumes:
  db-data: